visualize:
  surfaces: true
  resultant_point: true
  initial_aligment: true
  final_aligment: true
plane_segmentation_threshold: 5
pcd_standart: './data/mesh.ply'
pcd_sample: './data/cloud-2.ply'
min_plane_size: 1000
horizontal_plane_coefficient: 3
vertical_plane_width: 2  # production 1
side_planes_coefficient: [10, 30]
preprocess:
  input_path: './raw_data/3'
  ouput_file: './data/cloud-3.ply'
  downsampling_voxel_size: 3  # production 1-2
alignment_voxel_size: 20
angles_format: 'zyx'
